version: "3"

networks:
  proxy:
    driver: overlay

volumes:
  mysql_volume:
    driver: local
  portainer_data:
    driver: local

services:
  reverse-proxy:
    image: "traefik:v2.0.0"
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTPS port
        #      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myhttpchallenge.acme.email=postmaster@kevinscooper.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    networks:
      - proxy


  ghost:
    image: ghost:latest
    restart: always
    environment:
      url: https://blog.kevinscooper.com
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DBPASSWORD}
      database__connection__database: ghost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`blog.kevinscooper.com`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    networks:
      - proxy
    volumes:
      - "./ghost_content:/var/lib/ghost/content"
    depends_on:
      - db

  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`port.kevinscooper.com`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myhttpchallenge"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - proxy

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  db:
    hostname: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - proxy
